### ISSUE TITLE
Comments on the protocol design and potential security issues

### ISSUE THREAD

**Issue by Lekensteyn** [TimeToogo/ff-proxy#3]
Hi Elliot,

I am sure you had lot of fun developing this and hopefully you learned a lot. :)

Just a few suggestions based on a quick look on the description in the README, config.c, crypto.c and ff_client.py:

- If you ever want to proxy from one protocol to another, consider using [socat](http://www.dest-unreach.org/socat/). It is as easy as `socat UDP-LISTEN:1234,fork TCP:example.com:80`. It also supports TLS, see the `SSL` type in the examples section of its [manual](http://www.dest-unreach.org/socat/doc/socat.html#ADDRESS_UDP_LISTEN).
- The key passed via the `--psk` option may be visible in the process list, in the Docker outputs, etc. At minimum you could try to scrub the process list. Environment variables are slightly better, but they have the same issues with respect to introspection by others. Passing it through a file (or volume/secrets mounted through Docker) is slightly more secure.
- If the "psk" is just a passphrase, it should use a proper key-stretching function such as Argon2 as opposed to padding it to zeroes.
- Your encryption protocol is vulnerable to replay attacks and is not forward-secret. The same encrypted data could be sent multiple times, and if the PSK is ever revealed, all previous and future communication will be compromised.

Note that your "zero latency" claim is not entirely accurate, your FF proxy still need to do the three-way handshake. There are ways to reduce latency on the network however:
- You can use TCP Fast Open ([RFC 7413](https://tools.ietf.org/html/rfc7413)). It is supported on Linux, enabled by default on Linux clients, but *off* by default for Linux servers. It allows data to be sent with the first TCP packet if the server was connected to before. Clients can also be configured to send it without the previous contact, but that may not work if the server does not support it.
- TLS 1.3 + TCP Fast Open or the UDP-based [QUIC](https://quicwg.org/) allow you to send "early data" with the first message. This usually requires you to have a session ticket from a previous session however.

Something that might not be taken into account by your design is packet reordering and loss. If you try to emulate a stream-oriented protocol on top of UDP, you become responsible for retransmission and reordering. From a quick look I don't see this addressed in the protocol design nor the client or server implementations.

If you are interested in protocol design, I suggest looking at [WireGuard](https://www.wireguard.com/) which has a 1-RTT handshake protocol on top of UDP. It uses ChaCha20-Poly1305 as [AEAD](https://en.wikipedia.org/wiki/Authenticated_encryption) as opposed to AES-GCM (which is also an AEAD), but more importantly, it keeps track of the record counters to avoid replay attacks. Try not to write your own cryptographic protocols though, you are most likely going to overlook something and make something insecure.

If you are up for another fun task, you could try to write a Wireshark dissector for your homegrown protocol. For this task I would recommend using Lua since its interface is slightly easier. See https://github.com/Lekensteyn/wireguard-dissector for an example and https://www.wireshark.org/docs/wsdg_html_chunked/wsluarm_modules.html for documentation.

Another suggestions is integrating with a fuzzer such as https://llvm.org/docs/LibFuzzer.html. I suspect that the option parser may explode, it looks a bit fishy. There are not sufficient length checks, something that is worrisome for a parser of external inputs.

**Comment by TimeToogo** [comment]
Holy cow! Thanks Peter for taking the the time to put together this review. It’s extremely informative and helpful. I’ll look into the potential issues you have described. 
Each one looks like it would be a solid improvement to the design.  

The only points of rebuttal I have are as follows:

- **zero latency** - this has definitely caused some controversy since true zero latency over a network is not possible. My thought process was that, the zero latency applies to the specific act of _sending_ the HTTP request over UDP since there is no prior packet exchange. And this is the whole operation from a clients point of view. Obviously even this is not true zero as it will take processing to construct and send out the packets over the wire. I’m keen to hear your thoughts on a better description for this.  
- **packet loss and reordering** - packet loss is intentionally ignored in the scope of this project. Since it’s use case is not for reliable data transmission and more about removing the feedback loops needed for typical HTTP/TCP. Packet reordering however should be taken into account however (although this hasn’t been well tested). The FF protocol does contain the necessary fields (chunk offset, chunk length) to reconstruct the complete payload regardless of any reordering that occurs. The proxy implementation should already handle this. 

Keen to hear your thoughts. 
Thanks again!

**Comment by Lekensteyn** [comment]
About zero latency, the first time I read the title, I actually thought it was about use of a zerocopy mechanism to reduce overhead on a single Linux system using [eBPF][1] which is why it caught by interest in the first place. The "zero latency" claim is as accurate as beer with 0.0% alcohol, you cannot achieve true zero latency with moving data unless the source and destination are the same. "zero roundtrips" might be more accurate but is also not entirely true since the upstream connection is still plain TCP.

To be honest, I did not realize that you were not interested in the server response at all, not even as an option. So using QUIC or TLS between the client and ff-proxy would add quite some overhead for no gain. Unless you are planning to reuse the session of course.

Some more food for thought:
- By introducing fragmentation and reassembly, you may actually increase latency due to [bufferbloat][2].
- If you can ensure that "ff-proxy" operates on trusted network paths, you could skip a lot of security mechanisms. However, if you intend to accept traffic from the public Internet, then you will need additional measures. Consider IP spoofing which can turn ff-proxy into an DoS enabler. The TCP three-way handshake aims to protect against this amplification attack.
- What use case (1) requires zero round trips, (2) permits the server response to be ignored, and (3) does not care about reliable delivery? What should the proxy do with a potentially large server response body? What if the upstream connection failed (network/HTTP errors)?

For cases where you need a "HTTP-like" protocol with optional reliability, you could consider [CoAP][3]. From the introduction of [RFC 7252][4]:
> One design goal of CoAP has been to keep
> message overhead small, thus limiting the need for fragmentation.

You did say it was for educational purposes and I was a bit hetitant to share this, but here is my opinion: I'd suggest studying existing work before creating a new protocol from scratch. Various RFCs for transport and application layer protocols such as QUIC, TLS, HTTP, CoAP, as well as informational documents describe a lot of considerations that you and I might not even have considered. Start with the requirements, then try to find a protocol/implementation that can satisfy that goal. Chances are that you end up with a stronger result compared to reinventing a wheel.


 [1]: https://blog.cloudflare.com/sockmap-tcp-splicing-of-the-future/
 [2]: https://en.wikipedia.org/wiki/Bufferbloat
 [3]: https://en.wikipedia.org/wiki/Constrained_Application_Protocol
 [4]: https://tools.ietf.org/html/7252

**Comment by TimeToogo** [comment]
> The "zero latency" claim is as accurate as beer with 0.0% alcohol

I agree with you. I've updated the description to zero roundtrips and apologise for misleading if you think that occurred, it was definitely not my intention. I'm happy with that since the main motivation for this was about removing the initial handshake enforced by TCP (even if that itself is somewhat misguided).

> By introducing fragmentation and reassembly, you may actually increase latency due to bufferbloat.

Noted and it's interesting to see how CoAP tackles this by minimising the protocol size overheads.

> However, if you intend to accept traffic from the public Internet, then you will need additional measures. Consider IP spoofing which can turn ff-proxy into an DoS enabler.

This point has been considered. By specifying a PSK, ff-proxy will disregard any incoming packets which do not successfully decrypt. Assuming the encryption scheme and key privacy hold, that should render any DoS attempts moot.

> What use case (1) requires zero round trips, (2) permits the server response to be ignored, and (3) does not care about reliable delivery

Not many I'm sure. I can only tell you one that I've come across: analytical data collection in distributed serverless environments. Specifically, collecting request data points within AWS Lambda @ Edge for which compute time (1) blocks the response from reaching the end user and (2) cost more due to extra granular billing. Initialising a connection via TCP to a remote server for each request can become very wasteful in this scenario hence a handshake-less protocol becomes appealing. Reduced reliability of delivery could also be an adequate trade-off given the data is used for more statistical purposes. I understand that even this is a stretch and am certain there are alternatives I haven't considered. 

> For cases where you need a "HTTP-like" protocol with optional reliability, you could consider CoAP. From the introduction of RFC 7252

Thank you for bringing CoAP to my attention. This is, by far, a more robust and considered choice for any production environments. I've added the CoAP protocol as a recommendation in the README.

Thanks for sharing your opinion. I agree with you completely that using existing standards should be a defacto option and will lead to better outcomes.

As this is a learning exercise for me I'm going to continue development where I see an opportunity to improve. You're previous points:

- Implement proper key-stretching function
- Perfect forwards secrecy - i'm not sure this is feasible in this scenario but will do some research

I'm going to work on the above points when I have some free time. 
Thanks for all your input so far.
You clearly have in-depth knowledge in this domain and I appreciate you taking the time to explain some of it to me.

**Comment by TimeToogo** [comment]
Hi @Lekensteyn,

Thanks for all your feedback, I've taken it onboard and have worked on addressing the issues that you have outlined.

In summary the following updates have been made:

- **Key stretching**: PBKDF2 is now used to perform key derivation with configuration iterations (see #12)
- **Forwards secrecy**: Improved, but not perfect, forwards secrecy since each request will derive a new key with a random salt passed to PBKDF2 (see #12)
- **Resistance to replay attacks**: Incoming requests contain a authenticated timestamp which will be compared to the host's time with configurable fudge factor (see #16).
- **Fuzzing**: Integrated libFuzzer as suggested and fixed memory leaks/crashes that were uncovered (see #17).

I believe this is sufficient to close this issue. If you have any other concerns feel free to comment or open a new issue.

Thanks for you guidance,
Elliot
